version: '3.8'

services:
  db:
    image: postgres:16
    container_name: vitrine_postgres
    restart: always
    environment:
      POSTGRES_USER: bah_user
      POSTGRES_PASSWORD: bah_password
      POSTGRES_DB: bah_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: vitrine_pgadmin
    restart: always
    environment:
    
      PGADMIN_DEFAULT_EMAIL: bmamadoualpha266@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
